config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  resources :users
  resources :dashboards, only: :index
  resources :todos, only: [:edit, :update]
  resources :projects do
    collection do
      get :details
    end
    resources :todos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  has_many :todos
  has_and_belongs_to_many :developers, ->{ where(role: 'developer') }, class_name: 'User'
  before_destroy { todos.destroy_all }
  
  def self.todos_with_status
    data = {}
    self.includes(:todos).each do |project|
      todos = project.todos
      array = [todos.done.length, todos.in_progress.length, todos.assigned.length]
      data[project.id] = array
    end
    data
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  enum status: [ :assigned, :in_progress, :done ]
  validates :description, presence: true
  belongs_to :project
  belongs_to :developer, ->{ where(role: 'developer') }, class_name: 'User', foreign_key: :user_id

  before_create :assign_status

  private
    def assign_status
      self.status = 'assigned'
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
         :registerable,
         :rememberable, 
         :validatable

  enum role: [ :admin, :developer ]

  has_many :todos
  has_and_belongs_to_many :projects

  after_initialize :set_default_role, if: :new_record?

  private
    def set_default_role
      self.role ||= :developer
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!

  def authorize_admin!
    unless current_user.admin?
      render_not_authorized_error
    end
  end

  def render_not_authorized_error
    respond_to do |format|
      format.html {
        render file: "#{Rails.root}/public/422",
        layout: false,
        status: 422
      }
    end
  end

  private

    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end

    def after_sign_in_path_for(resource)
      if resource.admin?
        stored_location_for(resource) || dashboards_path
      else
        stored_location_for(resource) || user_path(resource)
      end
    end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authorize_admin!

  def index
    @projects = Project.includes(:todos).all
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_admin!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully destroyed.' }
    end
  end

  def details
    render json: Project.todos_with_status
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, developer_ids: [])
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authorize_admin!, except: [:edit, :update]
  before_action :find_project, except: :count_per_status
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :check_todos_authority!, only: [:edit, :update], if: -> { current_user.developer? }

  def index
    @todos = @project.todos
  end

  def show
  end

  def new
    @todo = @project.todos.new
  end

  def edit
  end

  def create
    @todo = @project.todos.new(todo_params)
    respond_to do |format|
      if @todo.save
        format.html { redirect_to project_todos_path(@project), notice: 'Todo was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to redirect_path, notice: 'Todo was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to redirect_path, notice: 'Todo was successfully destroyed.' }
    end
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def find_project
      @project = Project.find(params[:project_id])
    end

    def todo_params
      params.require(:todo).permit(:description, :status, :user_id)
    end

    def check_todos_authority!
      unless @todo.user_id == current_user.id
        render_not_authorized_error
      end
    end

    def redirect_path
      if current_user.developer?
        user_path(current_user)
      else
        project_todos_path(@project)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin!, except: :show

  def index
    @admins = User.admin
    @developers = User.developer
  end

  def show
    @user = User.find(params[:id])
    if current_user.admin?
      @todos = @user.todos.includes(:project).order(created_at: :desc)
    else
      @todos = current_user.todos.includes(:project).order(created_at: :desc)
    end
    unless current_user.admin? || @user == current_user
      render_not_authorized_error
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/dashboards/_index.html.haml
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %script{src: "https://www.gstatic.com/charts/loader.js", type: "text/javascript"}
    :javascript
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(implementCharts);

      function implementCharts(data) {
        $.ajax({
          url: "/projects/details",
          dataType: "json",
          type: "GET",
          contentType: "application/json; charset=utf-8",
          success: function (data) {
            for(var project_id in data) {
              drawChart(project_id, data[project_id])
            }
          },
          error: function (XMLHttpRequest, textStatus, errorThrown) {
            alert('Something went wrong!');
          }
        });
      }

      function drawChart(project_id, data) {
        var done_count = data[0];
        var inprogress_count = data[1];
        var new_count = data[2];
        var data = google.visualization.arrayToDataTable([
          ['Task', 'Count per Status'],
          ['Done', done_count],
          ['In Progress', inprogress_count],
          ['New', new_count]
        ]);
        var options = {
          title: "ToDo's Count per Status",
          width:380,
          height:300
        };
        var project = "piechart_project_" + project_id
        console.log("project : " + project);
        var chart = new google.visualization.PieChart(document.getElementById(project));
        chart.draw(data, options);
      }

  %body
    %table.columns
    - projects.in_groups_of(3, false) do |row|
      .row
        - for project in row
          .col-lg-4.col-md-4.col-xs-12.thumb
            - if project.todos.present?
              %h4
                = project.title
              .chart{id: "piechart_project_#{project.id}"}
            - else
              %h4
                = project.title
              .empty_chart
                .empty_text No ToDO's Present

app/views/dashboards/index.html.haml
%h3 Welcome To Project Management
%br

%table.table.dashboard_table
  %tr.border-bottom.dashed
    %th.dashed.bold-text Status
    - @projects.each do |project|
      %th.dashed.bold-text
        = project.title

  %tr.border-bottom.dashed
    %td.dashed.bold-text Done
    - @projects.each do |project|
      %td.dashed
        %ul{style: 'list-style-type: none;'}
          - project.todos.done.each do |todo|
            %li.li-item
              = todo.description

  %tr.border-bottom.dashed
    %td.dashed.bold-text In Progress
    - @projects.each do |project|
      %td.dashed
        %ul{style: 'list-style-type: none;'}
          - project.todos.in_progress.each do |todo|
            %li.li-item
              = todo.description

  %tr.border-bottom.dashed
    %td.dashed.bold-text New
    - @projects.each do |project|
      %td.dashed
        %ul{style: 'list-style-type: none;'}
          - project.todos.assigned.each do |todo|
            %li.li-item
              = todo.description

%br
= render partial: 'index', locals: {projects: @projects}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  - if current_user.admin?
    %li= link_to 'Projects', projects_path
    %li= link_to 'Developers', users_path
  %li= link_to 'Sign out', destroy_user_session_path, method: 'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      - if user_signed_in?
        = link_to 'Dashboard', current_user.admin? ? dashboards_path : user_path(current_user),
          class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Project Management"
    %meta{content: "#{content_for?(:description) ? yield(:description) : "Let Me In"}", name: "description"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %header
      = render 'layouts/navigation'
    %main{role: "main"}
      = render 'layouts/messages'
      = yield

app/views/projects/_form.html.haml
.container-fluid
  = form_for @project do |f|
    - if @project.errors.any?
      #error_explanation
        %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
        %ul
          - @project.errors.full_messages.each do |message|
            %li= message

    .form-group.row
      %label.col-sm-2.col-form-label
        = f.label :title
      .col-sm-6
        = f.text_field :title, class: 'form-control'

    - if action_name == 'edit'
      .form-group.row
        %label.col-sm-2.col-form-label
          Developers
        .col-sm-6
          = f.collection_select(:developer_ids, User.developer.collect, :id, :email, { include_blank: "Select developers" }, { class: 'search-and-select form-control', multiple: true })

    .form-group.actions.row
      .col-sm-2
        = f.submit 'Save', class: 'btn btn-success'
      .col-sm-2
        = link_to 'Back', projects_path, class: 'btn btn-info'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

app/views/projects/index.html.haml
%h1 All Projects

.table-responsive
  %table.table.table-hover
    %thead.thead-light
      %tr
        %th Title
        %th ToDo's Count
        %th Developer's Count
        %th Actions
    %tbody
      - @projects.each do |project|
        %tr
          %td= project.title
          %td= project.todos.count
          %td= project.developers.count
          %td
            .row
              .dropdown.col-sm-3
                %button.btn.btn-warning.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
                  Options
                .dropdown-menu
                  %li= link_to "List ToDo's", project_todos_path(project)
                  %li= link_to 'Add ToDo', new_project_todo_path(project)
                  %li= link_to 'Add Developer', edit_project_path(project)
              .dropdown.col-sm-3
                %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
                  Operations
                .dropdown-menu
                  %li= link_to 'Edit', edit_project_path(project)
                  %li= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'New Project', new_project_path, class: 'btn btn-success'

app/views/projects/new.html.haml
%h1 New project

= render 'form'

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @project.title

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path

app/views/todos/_form.html.haml
.container-fluid
  = form_for [@project, @todo] do |f|
    - if @todo.errors.any?
      #error_explanation
        %h2= "#{pluralize(@todo.errors.count, "error")} prohibited this todo from being saved:"
        %ul
          - @todo.errors.full_messages.each do |message|
            %li= message

    .form-group.row
      = f.hidden_field :project_id, value: @project.id
      %label.col-sm-2.col-form-label
        = f.label :description
      .col-sm-6
        = f.text_field :description, class: 'form-control-plaintext form-control'

    .form-group.row
      %label.col-sm-2.col-form-label
        = f.label :developer
      .col-sm-6
        = f.collection_select(:user_id, @project.developers.collect, :id, :email, {include_blank: "Select developer"}, { class: 'form-control' })

    .form-group.actions.row
      .col-sm-2
        = f.submit 'Save', class: 'btn btn-success'
      .col-sm-2
        = link_to 'Back', project_todos_path(@project), class: 'btn btn-info'

app/views/todos/edit.html.haml
.container-fluid
  %h1 Change Status
  = form_for [@project, @todo] do |f|
    - if @todo.errors.any?
      #error_explanation
        %h2= "#{pluralize(@todo.errors.count, "error")} prohibited this todo from being saved:"
        %ul
          - @todo.errors.full_messages.each do |message|
            %li= message

    .form-group.row
      = f.hidden_field :project_id, value: @project.id

    .form-group.row
      %label.col-sm-2.col-form-label
        = f.label :status
      .col-sm-10
        = f.select :status, Todo.statuses.map {|key, value| [key.titleize, key]}, { prompt: 'Change Status'}, class: 'form-control', required: true
        
    .form-group.actions.row
      .col-sm-2
        = f.submit 'Save', class: 'btn btn-success'
      .col-sm-2
        = link_to 'Back', project_todo_path(@project, @todo), class: 'btn btn-info'

app/views/todos/index.html.haml
%h1 Listing todos

%table.table.table-hover
  %thead.thead-light
    %tr
      %th Description
      %th Status
      %th Developer
      %th Action
  %tbody
    - @todos.each do |todo|
      %tr
        %td= todo.description
        %td= todo.status.titleize
        %td= todo.developer.email
        %td
          = link_to 'Show', project_todo_path(@project, todo), class: 'btn btn-primary'
          = link_to 'Edit', edit_project_todo_path(@project, todo), class: 'btn btn-info'
          = link_to 'Destroy', project_todo_path(@project, todo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

%br

= link_to 'New Todo', new_project_todo_path(@project), class: 'btn btn-success'

app/views/todos/new.html.haml
%h1 Create Task
%br
= render 'form'

app/views/todos/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @todo.description
%p
  %b Status:
  = @todo.status
%p
  %b User:
  = @todo.developer.email

= link_to 'Edit', edit_project_todo_path(@todo.project, @todo), class: 'btn btn-info'
\|
= link_to 'Back', project_todos_path(@todo.project), class: 'btn btn-warning'

app/views/users/_developer.html.haml
%td= link_to developer.email, developer
%td= link_to developer.name, developer

app/views/users/index.html.haml
.container
  .row
    %h3 Developers
    .column
      
  %table.table.table-hover
    %thead.thead-light
      %tr
        %th Email
        %th Projects's count
        %th ToDo's count
        %th Action
    %tbody
      - @developers.each do |developer|
        %tr
          %td= developer.email
          %td= developer.todos.count
          %td= developer.projects.count
          %td= link_to 'Details', user_path(developer), class: 'btn btn-info'

app/views/users/show.html.haml
.container-fluid
%h3
  = @user.email

%br
- if @todos.present?
  %table.table.table-hover
    %thead.thead-light
      %tr
        %th Project
        %th Description
        %th Status
        %th Actions

    %tbody
      - @todos.each do |todo|
        %tr
          %td= todo.project.title
          %td= todo.description
          %td= todo.status.titleize
          %td
            = link_to 'Change Status', edit_project_todo_path(todo.project, todo), class: 'btn btn-info'
- else
  %h4 No ToDo's Assigned
%br
- if current_user.admin?
  = link_to 'Back', users_path, class: 'btn btn-warning'          